use sea_orm_migration::prelude::*;

use crate::m20260330_000006_create_runs::Runs;

/// Creates the run_flags table for tracking review requests on runs.
/// Has a UNIQUE constraint on run_id (one active flag per run).
#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(RunFlags::Table)
                    .if_not_exists()
                    .col(ColumnDef::new(RunFlags::Id).text().not_null().primary_key())
                    .col(
                        ColumnDef::new(RunFlags::RunId)
                            .text()
                            .not_null()
                            .unique_key(),
                    )
                    .col(ColumnDef::new(RunFlags::Reason).text().not_null())
                    .col(ColumnDef::new(RunFlags::Note).text())
                    .col(
                        ColumnDef::new(RunFlags::HideWhilePending)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(RunFlags::AutoGenerated)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(ColumnDef::new(RunFlags::CreatedAt).text().not_null())
                    .col(ColumnDef::new(RunFlags::ResolvedAt).text())
                    .foreign_key(
                        ForeignKey::create()
                            .from(RunFlags::Table, RunFlags::RunId)
                            .to(Runs::Table, Runs::Id),
                    )
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(RunFlags::Table).to_owned())
            .await
    }
}

#[derive(DeriveIden)]
enum RunFlags {
    Table,
    Id,
    RunId,
    Reason,
    Note,
    HideWhilePending,
    AutoGenerated,
    CreatedAt,
    ResolvedAt,
}
