//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

#[allow(unused_imports)]
pub mod prelude;

pub mod bodies;
pub mod characters;
pub mod cups;
pub mod drink_types;
pub mod gliders;
pub mod run_flags;
pub mod runs;
pub mod tracks;
pub mod users;
pub mod wheels;
