//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "runs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    pub track_id: i32,
    pub character_id: i32,
    pub body_id: i32,
    pub wheels_id: i32,
    pub glider_id: i32,
    pub track_time: i32,
    pub lap1_time: i32,
    pub lap2_time: i32,
    pub lap3_time: i32,
    #[sea_orm(column_type = "Text")]
    pub drink_type_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub photo_path: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bodies::Entity",
        from = "Column::BodyId",
        to = "super::bodies::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Bodies,
    #[sea_orm(
        belongs_to = "super::characters::Entity",
        from = "Column::CharacterId",
        to = "super::characters::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Characters,
    #[sea_orm(
        belongs_to = "super::drink_types::Entity",
        from = "Column::DrinkTypeId",
        to = "super::drink_types::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DrinkTypes,
    #[sea_orm(
        belongs_to = "super::gliders::Entity",
        from = "Column::GliderId",
        to = "super::gliders::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Gliders,
    #[sea_orm(has_many = "super::run_flags::Entity")]
    RunFlags,
    #[sea_orm(
        belongs_to = "super::tracks::Entity",
        from = "Column::TrackId",
        to = "super::tracks::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Tracks,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
    #[sea_orm(
        belongs_to = "super::wheels::Entity",
        from = "Column::WheelsId",
        to = "super::wheels::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Wheels,
}

impl Related<super::bodies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bodies.def()
    }
}

impl Related<super::characters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Characters.def()
    }
}

impl Related<super::drink_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DrinkTypes.def()
    }
}

impl Related<super::gliders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Gliders.def()
    }
}

impl Related<super::run_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RunFlags.def()
    }
}

impl Related<super::tracks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tracks.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::wheels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wheels.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
