//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sessions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub created_by: String,
    #[sea_orm(column_type = "Text")]
    pub host_id: String,
    #[sea_orm(column_type = "Text")]
    pub ruleset: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub least_played_drink_category: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub last_activity_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CreatedByUser,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::HostId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    HostUser,
    #[sea_orm(has_many = "super::session_participants::Entity")]
    SessionParticipants,
    #[sea_orm(has_many = "super::session_races::Entity")]
    SessionRaces,
}

impl Related<super::session_participants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SessionParticipants.def()
    }
}

impl Related<super::session_races::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SessionRaces.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
