//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tracks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    #[sea_orm(column_type = "Text", unique)]
    pub name: String,
    pub cup_id: i32,
    pub position: i32,
    #[sea_orm(column_type = "Text")]
    pub image_path: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cups::Entity",
        from = "Column::CupId",
        to = "super::cups::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Cups,
    #[sea_orm(has_many = "super::runs::Entity")]
    Runs,
    #[sea_orm(has_many = "super::session_races::Entity")]
    SessionRaces,
}

impl Related<super::cups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cups.def()
    }
}

impl Related<super::runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Runs.def()
    }
}

impl Related<super::session_races::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SessionRaces.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
