//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", unique)]
    pub username: String,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub email: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub password_hash: String,
    pub preferred_character_id: Option<i32>,
    pub preferred_body_id: Option<i32>,
    pub preferred_wheel_id: Option<i32>,
    pub preferred_glider_id: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub preferred_drink_type_id: Option<String>,
    pub refresh_token_version: i32,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bodies::Entity",
        from = "Column::PreferredBodyId",
        to = "super::bodies::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Bodies,
    #[sea_orm(
        belongs_to = "super::characters::Entity",
        from = "Column::PreferredCharacterId",
        to = "super::characters::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Characters,
    #[sea_orm(
        belongs_to = "super::drink_types::Entity",
        from = "Column::PreferredDrinkTypeId",
        to = "super::drink_types::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DrinkTypes,
    #[sea_orm(
        belongs_to = "super::gliders::Entity",
        from = "Column::PreferredGliderId",
        to = "super::gliders::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Gliders,
    #[sea_orm(has_many = "super::runs::Entity")]
    Runs,
    #[sea_orm(has_many = "super::session_participants::Entity")]
    SessionParticipants,
    #[sea_orm(
        belongs_to = "super::wheels::Entity",
        from = "Column::PreferredWheelId",
        to = "super::wheels::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Wheels,
}

impl Related<super::bodies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bodies.def()
    }
}

impl Related<super::characters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Characters.def()
    }
}

impl Related<super::drink_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DrinkTypes.def()
    }
}

impl Related<super::gliders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Gliders.def()
    }
}

impl Related<super::runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Runs.def()
    }
}

impl Related<super::wheels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wheels.def()
    }
}

impl Related<super::session_participants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SessionParticipants.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
