//! Validated string newtypes.
//!
//! Companion to [`super::ids`] — where `ids.rs` makes "wrong-id-in-this-arg"
//! a compile error, this module makes "unvalidated-string-in-this-arg" a
//! compile error. Each newtype wraps a `String` and runs sanitization +
//! validation in its constructor, so a downstream caller that holds a
//! [`Username`] can trust it is 1–30 characters with no leading/trailing
//! whitespace without re-checking. See `coding-standards/rust.md` § 2.
//!
//! Constructors are the boundary: at HTTP request handlers, build the
//! newtype with `try_from(raw_string)?`, map the parse error to
//! [`Error::BadRequest`], and pass the newtype the rest of the way. At the
//! entity boundary (when reading a row), use the `from_db` helper to map a
//! constructor failure to [`Error::Internal`] — a stored value that fails
//! validation is data corruption, not a client error.
//!
//! Derive choices follow the pattern from [`super::ids`]: full derives on
//! types that flow through the API contract ([`Username`], [`EmailAddress`],
//! [`DrinkTypeName`], [`ImagePath`], [`RunNotes`]); restricted derives on
//! secrets ([`Password`], [`PasswordHash`]) to keep them out of logs and
//! wire payloads.

use nutype::nutype;

use crate::error::Error;

// ── Predicates and sanitizers (free functions for clarity) ───────────────

fn is_argon2_phc_hash(s: &str) -> bool {
    // PHC strings for any Argon2 variant. We only ever produce `$argon2id$`,
    // but accept all three so a hash generated by an older crate version
    // still parses. argon2's own `PasswordHash::new` performs the strict
    // parse downstream when verifying.
    s.starts_with("$argon2id$") || s.starts_with("$argon2i$") || s.starts_with("$argon2d$")
}

fn looks_like_email(s: &str) -> bool {
    // Intentionally minimal: RFC 5322 is famously not regex-checkable, and
    // the canonical answer is "send a confirmation email." We enforce the
    // bare minimum that catches obvious typos: exactly one `@`, with at
    // least one character on each side, and a `.` in the domain part.
    // Destructure-on-iterator avoids the per-call `Vec<&str>` allocation
    // that a `.collect()` form would carry.
    let mut parts = s.split('@');
    matches!(
        (parts.next(), parts.next(), parts.next()),
        (Some(local), Some(domain), None)
            if !local.is_empty() && !domain.is_empty() && domain.contains('.')
    )
}

// ── User-facing string newtypes ──────────────────────────────────────────

/// A user-chosen account name. 1–30 characters after trimming surrounding
/// whitespace.
///
/// `len_char_min`/`max` count Unicode scalar values (matching the existing
/// `username.chars().count()` check in the register handler). Trimming
/// happens before length validation, so `"  "` is rejected as empty rather
/// than passing as a 2-char username.
#[nutype(
    sanitize(trim),
    validate(len_char_min = 1, len_char_max = 30),
    derive(
        Debug,
        Clone,
        PartialEq,
        Eq,
        Hash,
        Display,
        AsRef,
        Serialize,
        Deserialize,
        TryFrom,
    )
)]
pub struct Username(String);

impl Username {
    /// Parse a username read from the database (typically `users.username`
    /// or a JOIN result aliasing it). Mirrors [`PasswordHash::from_db`] and
    /// [`ImagePath::from_db`]: a stored value that fails the newtype's
    /// invariant is data corruption, so the failure surfaces as
    /// [`Error::Internal`] rather than a client-facing `BadRequest`.
    ///
    /// # Errors
    ///
    /// Returns [`Error::Internal`] if the stored value fails the trim +
    /// 1–30 character check. The `column` argument is woven into the error
    /// context so logs name the source column (e.g.
    /// `"Invalid username in users.username"`).
    pub fn from_db(s: String, column: &'static str) -> Result<Self, Error> {
        Self::try_from(s).map_err(|e| {
            Error::Internal(
                anyhow::Error::msg(e.to_string()).context(format!("Invalid username in {column}")),
            )
        })
    }
}

/// An email address. Stored as the lowercased, trimmed form; rejection is
/// limited to obvious-shape checks (see [`looks_like_email`]). 3–320
/// characters (320 is the RFC 5321 upper bound for `local@domain`).
///
/// Currently unused on the write path — the `users.email` column is always
/// `None` at insert time — but defined here so that when the email-capture
/// flow lands the validation already exists at the boundary.
#[nutype(
    sanitize(trim, lowercase),
    validate(len_char_min = 3, len_char_max = 320, predicate = looks_like_email),
    derive(
        Debug,
        Clone,
        PartialEq,
        Eq,
        Hash,
        Display,
        AsRef,
        Serialize,
        Deserialize,
        TryFrom,
    ),
)]
pub struct EmailAddress(String);

/// A plaintext password as submitted by the user. 8–128 characters.
///
/// Deliberately *missing* `Debug`, `Display`, `Serialize`, and `Deserialize`
/// derives: passwords must never reach a log line, a `tracing` field, a
/// JSON response, or the bug-report attachment surface. The only way out
/// is the explicit [`into_inner`](Self::into_inner) call, which makes
/// leakage grep-visible in review.
///
/// Validation length matches the existing register/change-password checks
/// (`body.password.len() < 8 || > 128`). The original check counted bytes;
/// `len_char_min`/`max` count characters. For ASCII passwords the two are
/// identical; for multi-byte passwords the new behavior is slightly more
/// permissive (a 4-codepoint password with 4-byte glyphs was previously
/// allowed at 16 bytes but rejected at 4 chars — the char count is the
/// user-visible quantity and matches what password UIs typically display).
#[nutype(validate(len_char_min = 8, len_char_max = 128), derive(AsRef, TryFrom))]
pub struct Password(String);

/// An Argon2id password hash in PHC string format.
///
/// Constructed by [`crate::services::auth::hash_password`]; round-trips
/// through the `users.password_hash` column. The constructor only checks
/// the variant prefix — the full PHC parse happens in `verify_password`
/// via `argon2::password_hash::PasswordHash::new`, which produces a
/// targeted error if the body is malformed.
///
/// Like [`Password`], deliberately missing `Display` so the hash can't
/// accidentally land in a log message via `tracing::field::display`.
/// `Debug` is included because the hash isn't secret in the same way the
/// plaintext is — it's stored at rest and reproducible from the password —
/// and `Debug` is useful for assertion failures in tests.
#[nutype(
    validate(predicate = is_argon2_phc_hash),
    derive(Debug, Clone, AsRef, Serialize, Deserialize, TryFrom),
)]
pub struct PasswordHash(String);

impl PasswordHash {
    /// Parse a hash read from the `users.password_hash` column.
    ///
    /// # Errors
    ///
    /// Returns [`Error::Internal`] if the stored value doesn't start with a
    /// known Argon2 variant prefix. Data corruption only — should never
    /// happen, but we'd rather surface a clear 500 than attempt to verify
    /// against a malformed hash and get a confusing argon2 error later.
    pub fn from_db(s: String) -> Result<Self, Error> {
        Self::try_from(s).map_err(|e| {
            Error::Internal(
                anyhow::Error::msg(e.to_string()).context("Invalid hash in users.password_hash"),
            )
        })
    }
}

// ── Domain-data string newtypes ──────────────────────────────────────────

/// The user-facing name of a drink type. 1–200 characters after trim.
///
/// Mirrors the existing route-level check in
/// [`crate::routes::drink_types::create_drink_type`].
#[nutype(
    sanitize(trim),
    validate(len_char_min = 1, len_char_max = 200),
    derive(
        Debug,
        Clone,
        PartialEq,
        Eq,
        Hash,
        Display,
        AsRef,
        Serialize,
        Deserialize,
        TryFrom,
    )
)]
pub struct DrinkTypeName(String);

/// A path to a static image asset (track preview, character portrait, etc.).
///
/// Populated by seed data, surfaced in `GET /api/v1/game-data/*` responses.
/// The newtype's job is mostly documentational at this stage — there's no
/// user-input path that constructs one — but it lets the response DTOs say
/// `image_path: ImagePath` instead of `image_path: String` and catches
/// hand-edited seed rows that omit the value.
///
/// `sanitize(trim) + len_char_min = 1` matches the shape used by
/// [`Username`] / [`DrinkTypeName`] / [`RunNotes`]: surrounding whitespace
/// is normalized, then the trimmed result must be non-empty. A corrupt
/// seed row like `"  /foo  "` becomes `"/foo"` rather than surviving with
/// the whitespace intact.
#[nutype(
    sanitize(trim),
    validate(len_char_min = 1, len_char_max = 500),
    derive(
        Debug,
        Clone,
        PartialEq,
        Eq,
        Hash,
        Display,
        AsRef,
        Serialize,
        Deserialize,
        TryFrom,
    )
)]
pub struct ImagePath(String);

impl ImagePath {
    /// Parse an image path read from a seeded lookup-table row.
    ///
    /// # Errors
    ///
    /// Returns [`Error::Internal`] if the stored path is empty or excessively
    /// long. Data corruption / mis-edited seed only.
    pub fn from_db(s: String, column: &'static str) -> Result<Self, Error> {
        Self::try_from(s).map_err(|e| {
            Error::Internal(
                anyhow::Error::msg(e.to_string())
                    .context(format!("Invalid image path in {column}")),
            )
        })
    }
}

/// Free-form notes on a run. Up to 2000 characters after trim.
///
/// Currently always `None` at insert time (the `runs.notes` column is
/// reserved for a future "add a note to your run" UI). Defined here so the
/// invariant ships with the newtype rather than appearing inline whenever
/// the feature lands.
#[nutype(
    sanitize(trim),
    validate(len_char_max = 2000),
    derive(
        Debug,
        Clone,
        PartialEq,
        Eq,
        Hash,
        Display,
        AsRef,
        Serialize,
        Deserialize,
        TryFrom,
    )
)]
pub struct RunNotes(String);

#[cfg(test)]
mod tests {
    use proptest::prelude::*;

    use super::*;

    // ── Username ─────────────────────────────────────────────────────

    #[test]
    fn test_username_accepts_typical_name() {
        let u = Username::try_from("alice".to_string()).unwrap();
        assert_eq!(u.as_ref(), "alice");
    }

    #[test]
    fn test_username_trims_surrounding_whitespace() {
        let u = Username::try_from("  alice  ".to_string()).unwrap();
        assert_eq!(u.as_ref(), "alice");
    }

    #[test]
    fn test_username_rejects_empty() {
        Username::try_from(String::new()).unwrap_err();
    }

    #[test]
    fn test_username_rejects_whitespace_only() {
        // After `sanitize(trim)` the result is empty, which fails the
        // `len_char_min = 1` check.
        Username::try_from("   ".to_string()).unwrap_err();
    }

    #[test]
    fn test_username_rejects_too_long() {
        let s = "a".repeat(31);
        Username::try_from(s).unwrap_err();
    }

    #[test]
    fn test_username_accepts_exactly_thirty_chars() {
        let s = "a".repeat(30);
        Username::try_from(s).unwrap();
    }

    #[test]
    fn test_username_char_count_not_byte_count() {
        // 30 multi-byte chars (each 4 bytes in UTF-8) = 120 bytes but
        // exactly 30 chars, so it should be accepted.
        let s = "🏎".repeat(30);
        Username::try_from(s).unwrap();
    }

    #[test]
    fn test_username_from_db_round_trip() {
        let u = Username::from_db("alice".to_string(), "users.username").unwrap();
        assert_eq!(u.as_ref(), "alice");
    }

    #[test]
    fn test_username_from_db_maps_corruption_to_internal_with_column() {
        let err = Username::from_db(String::new(), "users.username").unwrap_err();
        let Error::Internal(chain) = err else {
            panic!("expected Internal, got {err:?}");
        };
        assert!(format!("{chain:#}").contains("users.username"));
    }

    // ── EmailAddress ────────────────────────────────────────────────

    #[test]
    fn test_email_accepts_typical_address() {
        let e = EmailAddress::try_from("alice@example.com".to_string()).unwrap();
        assert_eq!(e.as_ref(), "alice@example.com");
    }

    #[test]
    fn test_email_lowercases() {
        let e = EmailAddress::try_from("Alice@Example.COM".to_string()).unwrap();
        assert_eq!(e.as_ref(), "alice@example.com");
    }

    #[test]
    fn test_email_rejects_no_at_sign() {
        EmailAddress::try_from("aliceexample.com".to_string()).unwrap_err();
    }

    #[test]
    fn test_email_rejects_no_dot_in_domain() {
        EmailAddress::try_from("alice@example".to_string()).unwrap_err();
    }

    #[test]
    fn test_email_rejects_multiple_at_signs() {
        EmailAddress::try_from("a@b@example.com".to_string()).unwrap_err();
    }

    // ── Password ────────────────────────────────────────────────────

    #[test]
    fn test_password_accepts_minimum_length() {
        let s = "a".repeat(8);
        Password::try_from(s).unwrap();
    }

    #[test]
    fn test_password_accepts_maximum_length() {
        let s = "a".repeat(128);
        Password::try_from(s).unwrap();
    }

    #[test]
    fn test_password_rejects_too_short() {
        let s = "a".repeat(7);
        // `Password` intentionally omits `Debug` (no plaintext in panics/logs),
        // so `.err().expect(...)` stands in for `.unwrap_err()`, which would
        // need `Password: Debug`.
        Password::try_from(s)
            .err()
            .expect("a 7-char password is below the 8-char minimum");
    }

    #[test]
    fn test_password_rejects_too_long() {
        let s = "a".repeat(129);
        Password::try_from(s)
            .err()
            .expect("a 129-char password is above the 128-char maximum");
    }

    // ── PasswordHash ────────────────────────────────────────────────

    #[test]
    fn test_password_hash_accepts_argon2id_prefix() {
        let s = "$argon2id$v=19$m=19456,t=2,p=1$AAAAAAAAAAAAAAAAAAA$AAAA".to_string();
        PasswordHash::try_from(s).unwrap();
    }

    #[test]
    fn test_password_hash_accepts_argon2i_prefix() {
        let s =
            "$argon2i$v=19$m=4096,t=3,p=1$c2FsdHNhbHQ$aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa".to_string();
        PasswordHash::try_from(s).unwrap();
    }

    #[test]
    fn test_password_hash_rejects_non_argon2_prefix() {
        PasswordHash::try_from("$bcrypt$junk".to_string()).unwrap_err();
    }

    #[test]
    fn test_password_hash_rejects_plaintext() {
        PasswordHash::try_from("hunter2".to_string()).unwrap_err();
    }

    #[test]
    fn test_password_hash_from_db_maps_corrupt_value_to_internal() {
        let err = PasswordHash::from_db("not-a-hash".to_string()).unwrap_err();
        assert!(matches!(err, Error::Internal(_)));
    }

    // ── DrinkTypeName ───────────────────────────────────────────────

    #[test]
    fn test_drink_type_name_accepts_typical() {
        let d = DrinkTypeName::try_from("IPA".to_string()).unwrap();
        assert_eq!(d.as_ref(), "IPA");
    }

    #[test]
    fn test_drink_type_name_trims() {
        let d = DrinkTypeName::try_from("  IPA  ".to_string()).unwrap();
        assert_eq!(d.as_ref(), "IPA");
    }

    #[test]
    fn test_drink_type_name_rejects_empty() {
        DrinkTypeName::try_from(String::new()).unwrap_err();
    }

    #[test]
    fn test_drink_type_name_rejects_whitespace_only() {
        DrinkTypeName::try_from("   ".to_string()).unwrap_err();
    }

    #[test]
    fn test_drink_type_name_rejects_too_long() {
        let s = "a".repeat(201);
        DrinkTypeName::try_from(s).unwrap_err();
    }

    #[test]
    fn test_drink_type_name_accepts_max_length() {
        let s = "a".repeat(200);
        DrinkTypeName::try_from(s).unwrap();
    }

    // ── ImagePath ───────────────────────────────────────────────────

    #[test]
    fn test_image_path_accepts_typical() {
        let p = ImagePath::try_from("/images/character/mario.png".to_string()).unwrap();
        assert_eq!(p.as_ref(), "/images/character/mario.png");
    }

    #[test]
    fn test_image_path_rejects_empty() {
        ImagePath::try_from(String::new()).unwrap_err();
    }

    #[test]
    fn test_image_path_rejects_whitespace_only() {
        ImagePath::try_from("   ".to_string()).unwrap_err();
    }

    #[test]
    fn test_image_path_from_db_carries_column_in_error() {
        let err = ImagePath::from_db(String::new(), "tracks.image_path").unwrap_err();
        let Error::Internal(chain) = err else {
            panic!("expected Internal, got {err:?}");
        };
        assert!(format!("{chain:#}").contains("tracks.image_path"));
    }

    // ── RunNotes ────────────────────────────────────────────────────

    #[test]
    fn test_run_notes_accepts_empty() {
        // RunNotes only caps the upper bound — an empty string is a valid
        // "user provided notes but they're blank" value, distinct from
        // `Option::None` ("user didn't provide notes at all").
        RunNotes::try_from(String::new()).unwrap();
    }

    #[test]
    fn test_run_notes_trims() {
        let n = RunNotes::try_from("  great race  ".to_string()).unwrap();
        assert_eq!(n.as_ref(), "great race");
    }

    #[test]
    fn test_run_notes_rejects_too_long() {
        let s = "a".repeat(2001);
        RunNotes::try_from(s).unwrap_err();
    }

    // ── Cross-newtype: serde round-trip ─────────────────────────────

    #[test]
    fn test_username_serializes_as_bare_string() {
        let u = Username::try_from("alice".to_string()).unwrap();
        let json = serde_json::to_string(&u).unwrap();
        assert_eq!(json, "\"alice\"");
    }

    #[test]
    fn test_username_deserializes_from_bare_string() {
        let json = "\"alice\"";
        let u: Username = serde_json::from_str(json).unwrap();
        assert_eq!(u.as_ref(), "alice");
    }

    #[test]
    fn test_username_deserialize_rejects_too_long() {
        let s = "a".repeat(31);
        let json = format!("\"{s}\"");
        let result: Result<Username, _> = serde_json::from_str(&json);
        result.unwrap_err();
    }

    // Property test: any string that passes Username's constructor round-trips
    // unchanged through serde JSON. The serde derive on a validated nutype
    // re-runs validation on deserialize, so a value built by `try_from` must
    // survive serialize → deserialize without mutation.
    proptest! {
        #[test]
        fn test_username_serde_round_trip(s in "[a-zA-Z0-9_]{1,30}") {
            let u = Username::try_from(s).unwrap();
            let json = serde_json::to_string(&u).unwrap();
            let recovered: Username = serde_json::from_str(&json).unwrap();
            prop_assert_eq!(u, recovered);
        }

        #[test]
        fn test_drink_type_name_serde_round_trip(s in "[a-zA-Z0-9 ]{1,50}") {
            // Skip cases where the input would be trimmed to empty (e.g. all
            // spaces); the regex above doesn't restrict surrounding spaces.
            prop_assume!(!s.trim().is_empty());
            let d = DrinkTypeName::try_from(s).unwrap();
            let json = serde_json::to_string(&d).unwrap();
            let recovered: DrinkTypeName = serde_json::from_str(&json).unwrap();
            prop_assert_eq!(d, recovered);
        }
    }
}
